const ACTION_TYPE_PREFIX = 'COPY_WRITING';

export const SET_COPY_WRITING_OPTIONS = `${ACTION_TYPE_PREFIX}/SET_COPY_WRITING_OPTIONS`;
export const SET_AUTO_WORD_ITEMS = `${ACTION_TYPE_PREFIX}/SET_AUTO_WORD_ITEMS`;
