export const marketingOffsets = [
  {
    rule_id: 'rule_20230926_ms_001',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'CCube_Leading_actors',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: [],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '기본 - diversity 1',
  },
  {
    rule_id: 'rule_20230926_ms_002',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'CCube_Leading_actors',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: [],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.75,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '기본 - diversity 2',
  },
  {
    rule_id: 'rule_20230926_ms_003',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'CCube_Leading_actors',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: [],
    model_parameter: {
      temperature: 0.6,
      top_k: 10,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '기본 - diversity 3',
  },
  {
    rule_id: 'rule_20230926_ms_004',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: [],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '주연 제외 - diversity 1',
  },
  {
    rule_id: 'rule_20230926_ms_005',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: [],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.75,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '주연 제외 - diversity 2',
  },
  {
    rule_id: 'rule_20230926_ms_006',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: [],
    model_parameter: {
      temperature: 0.6,
      top_k: 10,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '주연 제외 - diversity 3',
  },
  {
    rule_id: 'rule_20230926_ms_007',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'CCube_Leading_actors',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '트리거 포함 - diversity 1',
  },
  {
    rule_id: 'rule_20230926_ms_008',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'CCube_Leading_actors',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.75,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '트리거 포함 - diversity 2',
  },
  {
    rule_id: 'rule_20230926_ms_009',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'CCube_Leading_actors',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.6,
      top_k: 10,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '트리거 포함 - diversity 3',
  },
  {
    rule_id: 'rule_20230926_ms_010',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '주연 제외, 트리거 포함 - diversity 1',
  },
  {
    rule_id: 'rule_20230926_ms_011',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.75,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '주연 제외, 트리거 포함 - diversity 2',
  },
  {
    rule_id: 'rule_20230926_ms_012',
    essential_meta: [
      'title',
      'Exposure_Dtl_Genre',
      'Ccube_Meta_what',
      'Ccube_Meta_who',
      'Ccube_Meta_emotion',
      'Ccube_Meta_subgenre',
    ],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.6,
      top_k: 10,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '주연 제외, 트리거 포함 - diversity 3',
  },
];
