import { MidmGeneratingOptionPreset } from 'src/types';

export const GENIE_THEME_PATH_ID = 'GENIE_THEME';
export const GENIE_THEME_PATH_PREFIX = 'genie-theme';
export const GENIE_THEME_TITLE = '지니테마';

export const genieThemeMidmGeneratingOptionPresets: MidmGeneratingOptionPreset[] = [
  {
    rule_id: 'rule_20230926_cn_001',
    essential_meta: ['title', 'target_user', 'keywords'],
    additional_meta: [],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '기본 - diversity 1',
  },
  {
    rule_id: 'rule_20230926_cn_002',
    essential_meta: ['title', 'target_user', 'keywords'],
    additional_meta: [],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.75,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '기본 - diversity 2',
  },
  {
    rule_id: 'rule_20230926_cn_003',
    essential_meta: ['title', 'target_user', 'keywords'],
    additional_meta: [],
    model_parameter: {
      temperature: 0.6,
      top_k: 10,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '기본 - diversity 3',
  },
  {
    rule_id: 'rule_20230926_cn_004',
    essential_meta: ['title', 'keywords'],
    additional_meta: [],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '대상 고객 제외 - diversity 1',
  },
  {
    rule_id: 'rule_20230926_cn_005',
    essential_meta: ['title', 'keywords'],
    additional_meta: [],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.75,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '대상 고객 제외 - diversity 2',
  },
  {
    rule_id: 'rule_20230926_cn_006',
    essential_meta: ['title', 'keywords'],
    additional_meta: [],
    model_parameter: {
      temperature: 0.6,
      top_k: 10,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '대상 고객 제외 - diversity 3',
  },
  {
    rule_id: 'rule_20230926_cn_007',
    essential_meta: ['title', 'target_user', 'keywords'],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '트리거 포함 - diversity 1',
  },
  {
    rule_id: 'rule_20230926_cn_008',
    essential_meta: ['title', 'target_user', 'keywords'],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.75,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '트리거 포함 - diversity 2',
  },
  {
    rule_id: 'rule_20230926_cn_009',
    essential_meta: ['title', 'target_user', 'keywords'],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.6,
      top_k: 10,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '트리거 포함 - diversity 3',
  },
  {
    rule_id: 'rule_20230926_cn_010',
    essential_meta: ['title', 'keywords'],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '대상 고객 제외, 트리거 포함 - diversity 1',
  },
  {
    rule_id: 'rule_20230926_cn_011',
    essential_meta: ['title', 'keywords'],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.8,
      top_k: 30,
      top_p: 0.75,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '대상 고객 제외, 트리거 포함 - diversity 2',
  },
  {
    rule_id: 'rule_20230926_cn_012',
    essential_meta: ['title', 'keywords'],
    additional_meta: ['trigger_words'],
    model_parameter: {
      temperature: 0.6,
      top_k: 10,
      top_p: 0.95,
      repetition_penalty: 1.0,
      presence_penalty: 1.0,
      beam_width: 1,
      num_return_sequences: 1,
    },
    comment: '대상 고객 제외, 트리거 포함 - diversity 3',
  },
];
